language: java
jdk:
- oraclejdk8
script:
- if [[ "x$TRAVIS_BRANCH" == "xmaster" && "x$TRAVIS_PULL_REQUEST" == "xfalse" ]]; then GOAL=deploy; else GOAL=install; fi
- echo "Goal is " $GOAL
- mvn -f parent/pom.xml clean $GOAL
after_success:
- git clone --depth=1 -b gh-pages https://${GH_TOKEN}@github.com/PizzaFactory/modeling-features.git gh-pages
- cd gh-pages
- if [ "x$TRAVIS_PULL_REQUEST" == "xfalse" && "x$TRAVIS_BRANCH" == "xmaster" ]; then mvn process-resources install; fi
env:
  global:
  - MAVEN_OPTS=-Xmx1024m
  - PIZZAFACTORY_VERSION=8.5
  - GIT_COMMITTER_NAME="Masaki Muranaka"
  - GIT_COMMITTER_EMAIL="monaka@monami-ya.jp"
  - secure: "OeJL9mviSvqrTYtcZtABUvS3zseF931d3mlBjFRW0j5tPUnzAol6R5QmGjqzkthU13HYeMLq+iiEbzXOi+E/il4OcdzAc2vNhmfKtUejfW8Km65Phsfy7F5+/5aEQF47KoKeN6BA//xwTNy/qUYNuXA8fh3UqL/4IMyyPomCZ1ZNCBnAY2R3zituBsaNbOC2Nos7A9tkYaNnVMdkBlI3bbZVgZtI++cATsuZ3Lbv+u5Dgm17JZpBG+k2483sMcTQfU/LNTxDtlcokfcvqHU3Xnnx5FaVvuVwqFhvFOYv6KswJKMLsx/Sukc0ECCCvBxGeXNEDVYdNS3FqSqvz5ZZTw7EYazXUogyTSnXjky03utcC4hLEc2VKOp0EOHYWXdJhRUiSJxvoQb7Kro/LWOdB9vj4K48qdnYlnAbBtKa0HMAo50wlRvTqP4KzOIgMu7f9Yt1/iAQFNBTH8lcuPL3qQgTDXxWdqIY3AZTsbE3Mt6WXBQNvqfGA1jDYVQc5bTKp0E5FltyLq9Z9irvCN8k3J6O7xgTgXKhrBHAFApp8Lrn6BgpjCB4NU13XmiTxTn6AcTiNLlSmdmfRLmgXVT8civTFy2HX62nNOcPwYf4ucZFF/3z1AKcnfzS4m1JLkgKqCycMl6+II+F68VzSFcyu0xSccv71xOa43cEvKDcroU="
